name: sysadmins
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual triggered workflow.'
        default: 'Trigger Workflow'
        required: true
jobs:
  job1:
    runs-on: [self-hosted, Linux, X64, sysadmins]
    name: SysAdmins task
    steps:
    # - uses: actions/checkout@v2
    # - name: Start Minikube
    #   uses: medyagh/setup-minikube@master
    - name: Check pre-build cluster
      run: kubectl get pods -A
    - name: Build custom nginx image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t sysadmins-custom-nginx .
        echo -n "verifying images:"
        docker images        
    - name: Deploy to Minikube
      run:
        kubectl apply -f ./minikube-deploy.yaml
    - name: Test if URL is responding with curl
      run: |
        minikube service list
        minikube service nginx-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service nginx-service --url)  
