name: sysadmins
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual triggered workflow.'
        default: 'HelloWorld'
        required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Check the cluster
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t sysadmins-custom-nginx .
        echo -n "verifying images:"
        docker images        
    - name: Deploy to minikube
      run:
        kubectl apply -f ./minikube-deploy.yaml
    - name: Test service URLs
      run: |
        minikube service list
        minikube service nginx-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service nginx-service --url)  
